//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SXBModels
{
    using System;

    /// <summary>
    /// 用户表
    /// </summary>
    public partial class SYS_USER
    {
        /// <summary>
        /// 
        /// </summary>
        public string ROW_ID { get; set; }
        /// <summary>
        /// 用户名
        /// </summary>
        public string USERNAME { get; set; }
        /// <summary>
        /// 密码
        /// </summary>
        public string PASSWORD { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        public string CREATEUSER { get; set; }
        /// <summary>
        /// 最后更新时间
        /// </summary>
        public Nullable<System.DateTime> LASTDATE { get; set; }
        /// <summary>
        /// 最后更新人
        /// </summary>
        public string LASTUSER { get; set; }
        /// <summary>
        /// 1可用0不可用-1删除
        /// </summary>
        public Nullable<int> ENABLEFLAG { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string REMARK { get; set; }
    }
}
